# Generated by Django 6.0.3 on 2026-03-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200, verbose_name='title')),
                ('title2', models.CharField(max_length=200, verbose_name='title')),
                ('text1', models.TextField(help_text='text', verbose_name='desciption')),
                ('text2', models.TextField(help_text='text', verbose_name='desciption')),
                ('text3', models.TextField(help_text='text', verbose_name='desciption')),
                ('image1', models.ImageField(upload_to='about/')),
                ('image2', models.ImageField(upload_to='about/')),
                ('image3', models.ImageField(upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(help_text='text', verbose_name='desciption')),
                ('image', models.ImageField(upload_to='home/')),
            ],
        ),
    ]
