# Generated by Django 6.0.3 on 2026-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text',
            field=models.TextField(default='Default about text', help_text='text', verbose_name='desciption'),
        ),
        migrations.AddField(
            model_name='about',
            name='text4',
            field=models.TextField(default='Default about text', help_text='text', verbose_name='desciption'),
        ),
        migrations.AddField(
            model_name='about',
            name='text5',
            field=models.TextField(default='Default about text', help_text='text', verbose_name='desciption'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text1',
            field=models.TextField(default='Default about text', help_text='text', verbose_name='desciption'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text2',
            field=models.TextField(default='Default about text', help_text='text', verbose_name='desciption'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text3',
            field=models.TextField(default='Default about text', help_text='text', verbose_name='desciption'),
        ),
    ]
