# Generated by Django 6.0.3 on 2026-04-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about_text_about_text4_about_text5_alter_about_text1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title2',
            field=models.CharField(default='Default about text', max_length=200, verbose_name='title'),
        ),
    ]
