# Generated by Django 6.0.3 on 2026-03-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('icon', models.CharField(help_text='example: fas fa-heartbeat', max_length=50, verbose_name='icon')),
                ('img', models.ImageField(upload_to='departments/', verbose_name='photo')),
                ('decription', models.TextField(verbose_name='decription')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('decription', models.TextField(verbose_name='decription')),
                ('icon', models.CharField(help_text='example: bi bi-capsule', max_length=50, verbose_name='icon')),
                ('image', models.ImageField(upload_to='service/', verbose_name='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('specialty', models.CharField(max_length=100, verbose_name='specialty')),
                ('image', models.ImageField(upload_to='doctors/', verbose_name='photo')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkdin', models.URLField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='medinest.department', verbose_name='Department')),
            ],
        ),
    ]
