# Generated by Django 6.0.3 on 2026-04-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='decription',
        ),
        migrations.RemoveField(
            model_name='service',
            name='decription',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
    ]
