# Generated by Django 6.0.3 on 2026-04-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0002_remove_department_decription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('icon', models.CharField(help_text='example: fas fa-heartbeat', max_length=50, verbose_name='icon')),
                ('img', models.ImageField(upload_to='departments/', verbose_name='photo')),
                ('description', models.TextField(default='', verbose_name='description')),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='img',
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Featured Department'),
        ),
        migrations.AddField(
            model_name='department',
            name='procedures_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Procedures'),
        ),
        migrations.AddField(
            model_name='department',
            name='specialists_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Specialists'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Department Description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.CharField(blank=True, help_text='example: fas fa-heartbeat', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='medinest.departmentcategory'),
        ),
    ]
