# Generated by Django 6.0.3 on 2026-04-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0003_departmentcategory_remove_department_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='title'),
        ),
    ]
