# Generated by Django 6.0.3 on 2026-04-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0004_department_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='title',
        ),
        migrations.AddField(
            model_name='departmentcategory',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='title'),
        ),
    ]
