# Generated by Django 6.0.3 on 2026-04-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0005_remove_department_title_departmentcategory_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='departmentcategory',
            name='text',
            field=models.TextField(default='Default about text', help_text='text', verbose_name='desciption'),
        ),
        migrations.AddField(
            model_name='departmentcategory',
            name='text1',
            field=models.TextField(default='Default about text', help_text='text', verbose_name='desciption'),
        ),
        migrations.AddField(
            model_name='departmentcategory',
            name='text2',
            field=models.TextField(default='Default about text', help_text='text', verbose_name='desciption'),
        ),
        migrations.AddField(
            model_name='departmentcategory',
            name='text3',
            field=models.TextField(default='Default about text', help_text='text', verbose_name='desciption'),
        ),
    ]
