# Generated by Django 6.0.3 on 2026-04-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0006_remove_departmentcategory_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='department',
            name='procedures_count',
        ),
        migrations.RemoveField(
            model_name='department',
            name='specialists_count',
        ),
    ]
