# Generated by Django 6.0.3 on 2026-04-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0007_remove_department_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
    ]
