# Generated by Django 6.0.3 on 2026-04-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0008_remove_department_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('title', models.CharField(default='', max_length=150, verbose_name='title')),
                ('text', models.TextField(default='Default about text', help_text='text', verbose_name='desciption')),
                ('description', models.TextField(default='', verbose_name='description')),
            ],
        ),
    ]
