# Generated by Django 6.0.3 on 2026-04-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0010_contact_faq_testimonial_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
