# Generated by Django 6.0.3 on 2026-04-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0011_alter_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
