# Generated by Django 6.0.3 on 2026-04-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0013_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='value',
            field=models.CharField(default='', max_length=10, verbose_name="Doctor's number"),
        ),
    ]
