# Generated by Django 6.0.3 on 2026-04-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0014_department_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='value',
            new_name='doc_num',
        ),
        migrations.AddField(
            model_name='department',
            name='pro_num',
            field=models.CharField(default='', max_length=10, verbose_name='Procedures number'),
        ),
    ]
