# Generated by Django 6.0.3 on 2026-04-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0015_rename_value_department_doc_num_department_pro_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='linkdin',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='twitter',
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.CharField(default='', max_length=10, verbose_name='Experience years'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pro_num',
            field=models.CharField(default='', max_length=10, verbose_name='Procedures number'),
        ),
    ]
